<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'name' => 'Burger',
                'slug' => 'burger',
                'short_description' => 'Burger short description.',
                'description' => 'This is a tasty burger. Perfect for food lovers.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-BURGER',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/1.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pizza',
                'slug' => 'pizza',
                'short_description' => 'Pizza short description.',
                'description' => 'This is a tasty pizza. Perfect for food lovers.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-PIZZA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/2.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sandwich',
                'slug' => 'sandwich',
                'short_description' => 'Sandwich short description.',
                'description' => 'This is a tasty sandwich. Perfect for food lovers.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-SANDWICH',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/3.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'French Fries',
                'slug' => 'french-fries',
                'short_description' => 'French Fries short description.',
                'description' => 'Crispy golden French Fries served hot and fresh.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-FRENCH-FRIES',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/4.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hot Dog',
                'slug' => 'hot-dog',
                'short_description' => 'Hot Dog short description.',
                'description' => 'Tasty hot dog with sausage, mustard, and ketchup.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-HOT-DOG',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/5.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Shawarma',
                'slug' => 'shawarma',
                'short_description' => 'Shawarma short description.',
                'description' => 'Deliciously spiced shawarma wrap with tender meat.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-SHAWARMA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/6.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Fried Chicken',
                'slug' => 'fried-chicken',
                'short_description' => 'Fried Chicken short description.',
                'description' => 'Crispy and juicy fried chicken, golden and flavorful.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-FRIED-CHICKEN',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/7.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nuggets',
                'slug' => 'nuggets',
                'short_description' => 'Nuggets short description.',
                'description' => 'Tasty chicken nuggets, crispy on the outside, tender inside.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-NUGGETS',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/8.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pasta',
                'slug' => 'pasta',
                'short_description' => 'Pasta short description.',
                'description' => 'Creamy and cheesy pasta that melts in your mouth.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-PASTA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/9.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Noodles',
                'slug' => 'noodles',
                'short_description' => 'Noodles short description.',
                'description' => 'Steaming hot noodles cooked with veggies and spices.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-NOODLES',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/fast_food/10.jpg',
                'images' => '',
                'category_id' => 1,
                'brand_id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ================🥤 Beverages (9)=======================
            [
                'name' => 'Tea',
                'slug' => 'tea',
                'short_description' => 'Tea short description.',
                'description' => 'Refreshing hot tea brewed with aromatic leaves.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-TEA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/beverages/1.jpg',
                'images' => '',
                'category_id' => 2,
                'brand_id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Coffee',
                'slug' => 'coffee',
                'short_description' => 'Coffee short description.',
                'description' => 'Bold and aromatic coffee perfect for energy boost.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-COFFEE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/beverages/2.jpg',
                'images' => '',
                'category_id' => 2,
                'brand_id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Lemon Juice',
                'slug' => 'lemon-juice',
                'short_description' => 'Lemon Juice short description.',
                'description' => 'Cool and tangy lemon juice, perfect for refreshment.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-LEMON-JUICE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/beverages/3.jpg',
                'images' => '',
                'category_id' => 2,
                'brand_id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Lassi',
                'slug' => 'lassi',
                'short_description' => 'Lassi short description.',
                'description' => 'Traditional chilled yogurt-based lassi drink.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-LASSI',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/beverages/4.jpg',
                'images' => '',
                'category_id' => 2,
                'brand_id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Soft Drinks (Coca-Cola, Pepsi)',
                'slug' => 'soft-drinks',
                'short_description' => 'Soft Drinks short description.',
                'description' => 'Popular carbonated soft drinks like Coca-Cola and Pepsi.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-SOFT-DRINKS',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/beverages/5.jpg',
                'images' => '',
                'category_id' => 2,
                'brand_id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Energy Drink',
                'slug' => 'energy-drink',
                'short_description' => 'Energy Drink short description.',
                'description' => 'Energizing drink to keep you active and alert.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-ENERGY-DRINK',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/beverages/6.jpg',
                'images' => '',
                'category_id' => 2,
                'brand_id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Chocolate Shake',
                'slug' => 'chocolate-shake',
                'short_description' => 'Chocolate Shake short description.',
                'description' => 'Thick and creamy chocolate shake for dessert lovers.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-CHOCOLATE-SHAKE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/beverages/7.jpg',
                'images' => '',
                'category_id' => 2,
                'brand_id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Green Tea',
                'slug' => 'green-tea',
                'short_description' => 'Green Tea short description.',
                'description' => 'Healthy green tea with antioxidants and a mild taste.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-GREEN-TEA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/beverages/8.jpg',
                'images' => '',
                'category_id' => 2,
                'brand_id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mango Shake',
                'slug' => 'mango-shake',
                'short_description' => 'Mango Shake short description.',
                'description' => 'Delicious mango shake made with fresh ripe mangoes.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-MANGO-SHAKE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/beverages/9.jpg',
                'images' => '',
                'category_id' => 2,
                'brand_id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ========================== 🍰 Desserts & Sweets (10)================================
            [
                'name' => 'Ice Cream',
                'slug' => 'ice-cream',
                'short_description' => 'Delicious cold dessert for a sweet treat.',
                'description' => 'Smooth and creamy ice cream, perfect for hot days and dessert lovers.',
                'regular_price' => 80.00,
                'sale_price' => 70.00,
                'SKU' => 'SKU-ICECREAM',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/1.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cake',
                'slug' => 'cake',
                'short_description' => 'Soft and spongy dessert for celebrations.',
                'description' => 'A moist and flavorful cake, perfect for birthdays, parties, and dessert cravings.',
                'regular_price' => 150.00,
                'sale_price' => 130.00,
                'SKU' => 'SKU-CAKE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/2.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pastry',
                'slug' => 'pastry',
                'short_description' => 'Mini cake with rich flavors and cream.',
                'description' => 'A small, elegant pastry layered with cream and flavor, perfect for tea-time treats.',
                'regular_price' => 60.00,
                'sale_price' => 50.00,
                'SKU' => 'SKU-PASTRY',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/3.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Gulab Jamun',
                'slug' => 'gulab-jamun',
                'short_description' => 'Traditional sweet soaked in syrup.',
                'description' => 'Soft, round sweets soaked in rose-flavored sugar syrup — a classic South Asian delicacy.',
                'regular_price' => 40.00,
                'sale_price' => 35.00,
                'SKU' => 'SKU-GULABJAMUN',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/4.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rasgulla',
                'slug' => 'rasgulla',
                'short_description' => 'Soft cheese balls in sugary syrup.',
                'description' => 'Spongy and juicy Rasgulla made from chenna and soaked in light syrup. A Bengali favorite.',
                'regular_price' => 40.00,
                'sale_price' => 35.00,
                'SKU' => 'SKU-RASGULLA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/5.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Laddu',
                'slug' => 'laddu',
                'short_description' => 'Round sweet made from flour, ghee & sugar.',
                'description' => 'Delicious laddu made with gram flour, ghee, and sugar — a festive essential.',
                'regular_price' => 35.00,
                'sale_price' => 30.00,
                'SKU' => 'SKU-LADDU',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/6.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Kheer',
                'slug' => 'kheer',
                'short_description' => 'Sweet rice pudding with nuts & cardamom.',
                'description' => 'A rich and creamy traditional rice pudding garnished with dry fruits — served chilled or warm.',
                'regular_price' => 50.00,
                'sale_price' => 45.00,
                'SKU' => 'SKU-KHEER',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/7.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Falooda',
                'slug' => 'falooda',
                'short_description' => 'Layered dessert with vermicelli & ice cream.',
                'description' => 'Falooda is a rich dessert drink made with rose syrup, vermicelli, sabja seeds, and ice cream.',
                'regular_price' => 70.00,
                'sale_price' => 60.00,
                'SKU' => 'SKU-FALOODA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/8.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Halwa',
                'slug' => 'halwa',
                'short_description' => 'Rich and dense sweet made from ghee & semolina.',
                'description' => 'A traditional sweet made with ghee, semolina, nuts, and cardamom for a warm, comforting dessert.',
                'regular_price' => 45.00,
                'sale_price' => 40.00,
                'SKU' => 'SKU-HALWA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/9.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mishti Doi',
                'slug' => 'mishti-doi',
                'short_description' => 'Sweetened yogurt from Bengal.',
                'description' => 'A traditional Bengali dessert — fermented sweet yogurt with a caramel-like flavor.',
                'regular_price' => 50.00,
                'sale_price' => 45.00,
                'SKU' => 'SKU-MISHTIDOI',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/desserts_sweets/10.jpg',
                'images' => '',
                'category_id' => 3,
                'brand_id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // =====================🍛 Traditional Food (10)=============================
            [
                'name' => 'Biryani',
                'slug' => 'biryani',
                'short_description' => 'Aromatic rice dish with meat and spices.',
                'description' => 'Rich and flavorful biryani made with fragrant basmati rice, tender meat, and traditional spices.',
                'regular_price' => 180.00,
                'sale_price' => 160.00,
                'SKU' => 'SKU-BIRYANI',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 100,
                'image' => 'products/traditional_food/1.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Khichuri',
                'slug' => 'khichuri',
                'short_description' => 'Comforting rice-lentil dish.',
                'description' => 'Classic Bengali khichuri cooked with rice, lentils, and aromatic spices. Often served with egg or meat curry.',
                'regular_price' => 120.00,
                'sale_price' => 100.00,
                'SKU' => 'SKU-KHICHURI',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/traditional_food/2.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Panta Bhat',
                'slug' => 'panta-bhat',
                'short_description' => 'Fermented rice with mustard and chili.',
                'description' => 'Traditional Bengali dish of fermented rice served with mustard oil, green chili, and onion.',
                'regular_price' => 90.00,
                'sale_price' => 80.00,
                'SKU' => 'SKU-PANTABHAT',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/traditional_food/3.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dal Puri',
                'slug' => 'dal-puri',
                'short_description' => 'Crispy fried puri stuffed with spiced lentils.',
                'description' => 'Golden fried dal puris filled with seasoned lentils — perfect for snacks or traditional meals.',
                'regular_price' => 50.00,
                'sale_price' => 40.00,
                'SKU' => 'SKU-DALPURI',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/traditional_food/4.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Shorshe Ilish',
                'slug' => 'shorshe-ilish',
                'short_description' => 'Hilsa fish in mustard gravy.',
                'description' => 'Iconic Bengali dish with Ilish (Hilsa) fish simmered in mustard seed gravy and green chilies.',
                'regular_price' => 250.00,
                'sale_price' => 230.00,
                'SKU' => 'SKU-SHORSHEILISH',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 100,
                'image' => 'products/traditional_food/5.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pati Shapta',
                'slug' => 'pati-shapta',
                'short_description' => 'Traditional Bengali crepes with sweet filling.',
                'description' => 'Soft crepes filled with coconut and jaggery stuffing — a favorite during winter festivals.',
                'regular_price' => 60.00,
                'sale_price' => 55.00,
                'SKU' => 'SKU-PATISHAPTA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/traditional_food/6.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dim Bhuna',
                'slug' => 'dim-bhuna',
                'short_description' => 'Spicy egg curry cooked with onions and spices.',
                'description' => 'Eggs cooked in a rich, spicy onion-tomato gravy — best served with paratha or rice.',
                'regular_price' => 90.00,
                'sale_price' => 80.00,
                'SKU' => 'SKU-DIMBHUNA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/traditional_food/7.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Chingri Malai Curry',
                'slug' => 'chingri-malai-curry',
                'short_description' => 'Prawns in coconut milk curry.',
                'description' => 'Succulent prawns simmered in a creamy coconut gravy — a Bengali delicacy.',
                'regular_price' => 280.00,
                'sale_price' => 260.00,
                'SKU' => 'SKU-CHINGRIMALAI',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 100,
                'image' => 'products/traditional_food/8.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Aloo Bharta',
                'slug' => 'aloo-bharta',
                'short_description' => 'Mashed potatoes with mustard oil.',
                'description' => 'Comforting mashed potatoes flavored with mustard oil, onions, and green chilies.',
                'regular_price' => 35.00,
                'sale_price' => 30.00,
                'SKU' => 'SKU-ALOOBHARTA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/traditional_food/9.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dal Gosht',
                'slug' => 'dal-gosht',
                'short_description' => 'Lentils cooked with tender meat pieces.',
                'description' => 'A rich and hearty combination of split lentils and spiced mutton — a traditional Eid favorite.',
                'regular_price' => 200.00,
                'sale_price' => 180.00,
                'SKU' => 'SKU-DALGOSHT',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/traditional_food/10.jpg',
                'images' => '',
                'category_id' => 4,
                'brand_id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ==================🥗 Healthy Food (10)=============================
            [
                'name' => 'Mixed Salad',
                'slug' => 'mixed-salad',
                'short_description' => 'A refreshing bowl of assorted fresh vegetables.',
                'description' => 'This mixed salad offers a healthy mix of greens, tomatoes, cucumbers, and carrots. Ideal for a light and nutritious meal.',
                'regular_price' => 120.00,
                'sale_price' => 100.00,
                'SKU' => 'SKU-MIXED-SALAD',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/health_foods/1.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Boiled Vegetables',
                'slug' => 'boiled-vegetables',
                'short_description' => 'Lightly boiled nutritious vegetables.',
                'description' => 'A colorful plate of lightly boiled vegetables like carrots, beans, peas, and broccoli, perfect for a healthy diet.',
                'regular_price' => 110.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-BOILED-VEG',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/health_foods/2.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Soup',
                'slug' => 'soup',
                'short_description' => 'A warm and healthy bowl of soup.',
                'description' => 'Nourishing and delicious, this soup is packed with flavors from fresh vegetables and herbs.',
                'regular_price' => 90.00,
                'sale_price' => 80.00,
                'SKU' => 'SKU-SOUP',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/health_foods/3.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Brown Rice',
                'slug' => 'brown-rice',
                'short_description' => 'Nutritious brown rice rich in fiber.',
                'description' => 'Healthy alternative to white rice, this brown rice is full of nutrients and perfect for clean eating.',
                'regular_price' => 130.00,
                'sale_price' => 115.00,
                'SKU' => 'SKU-BROWN-RICE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/health_foods/4.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sprouts',
                'slug' => 'sprouts',
                'short_description' => 'Protein-rich fresh sprouts.',
                'description' => 'Fresh and crunchy sprouts packed with protein and nutrients. Great as a healthy snack or meal addition.',
                'regular_price' => 70.00,
                'sale_price' => 60.00,
                'SKU' => 'SKU-SPROUTS',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/health_foods/5.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Green Smoothie',
                'slug' => 'green-smoothie',
                'short_description' => 'A detoxifying green smoothie.',
                'description' => 'Blend of spinach, kale, green apple, and lemon. This green smoothie is perfect for detox and boosting energy.',
                'regular_price' => 150.00,
                'sale_price' => 130.00,
                'SKU' => 'SKU-GREEN-SMOOTHIE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/health_foods/6.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Oats Porridge',
                'slug' => 'oats-porridge',
                'short_description' => 'Creamy and wholesome oats porridge.',
                'description' => 'Made with rolled oats, milk, and honey, this porridge is a hearty and nutritious breakfast option.',
                'regular_price' => 90.00,
                'sale_price' => 75.00,
                'SKU' => 'SKU-OATS-PORRIDGE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/health_foods/7.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Grilled Chicken',
                'slug' => 'grilled-chicken',
                'short_description' => 'Lean and juicy grilled chicken.',
                'description' => 'Tender and well-seasoned grilled chicken breast, low in fat and high in protein.',
                'regular_price' => 180.00,
                'sale_price' => 160.00,
                'SKU' => 'SKU-GRILLED-CHICKEN',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 100,
                'image' => 'products/health_foods/8.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Greek Yogurt',
                'slug' => 'greek-yogurt',
                'short_description' => 'Thick and creamy Greek yogurt.',
                'description' => 'Rich in probiotics and protein, Greek yogurt is a delicious and healthy snack or breakfast base.',
                'regular_price' => 120.00,
                'sale_price' => 100.00,
                'SKU' => 'SKU-GREEK-YOGURT',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 100,
                'image' => 'products/health_foods/9.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Almonds & Nuts',
                'slug' => 'almonds-nuts',
                'short_description' => 'A healthy mix of almonds and other nuts.',
                'description' => 'Packed with healthy fats and protein, this nut mix is perfect for snacking or adding to meals.',
                'regular_price' => 200.00,
                'sale_price' => 180.00,
                'SKU' => 'SKU-NUTS-MIX',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 100,
                'image' => 'products/health_foods/10.jpg',
                'images' => '',
                'category_id' => 5,
                'brand_id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ========================🛒 Kacha Bazar (Grocery Items - 50)/Rice (5)=============
            [
                'name' => 'Bashmati Chal',
                'slug' => 'bashmati-chal',
                'short_description' => 'Finest long-grain Bashmati rice.',
                'description' => 'Bashmati Chal is known for its long grains and aromatic flavor, ideal for biryani and special dishes.',
                'regular_price' => 130.00,
                'sale_price' => 120.00,
                'SKU' => 'SKU-BASHMATI-CHAL',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/rice/1.jpg',
                'images' => '',
                'category_id' => 6, // Kacha Bazar
                'brand_id' => 19,   // Fresh Grocery
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Miniket Chal',
                'slug' => 'miniket-chal',
                'short_description' => 'Soft and polished Miniket rice.',
                'description' => 'Miniket Chal is a popular white rice in Bangladesh, known for its soft texture and great taste.',
                'regular_price' => 110.00,
                'sale_price' => 100.00,
                'SKU' => 'SKU-MINIKET-CHAL',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/rice/2.jpg',
                'images' => '',
                'category_id' => 6,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Atap Chal',
                'slug' => 'atap-chal',
                'short_description' => 'Locally processed Atap rice.',
                'description' => 'Atap Chal is semi-polished rice, commonly used for making pitha and traditional Bengali dishes.',
                'regular_price' => 90.00,
                'sale_price' => 80.00,
                'SKU' => 'SKU-ATAP-CHAL',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/rice/3.jpg',
                'images' => '',
                'category_id' => 6,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Chinigura Chal',
                'slug' => 'chinigura-chal',
                'short_description' => 'Aromatic Chinigura rice for pulao.',
                'description' => 'Chinigura Chal is a premium aromatic rice perfect for preparing pulao and other festive dishes.',
                'regular_price' => 140.00,
                'sale_price' => 130.00,
                'SKU' => 'SKU-CHINIGURA-CHAL',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/rice/4.jpg',
                'images' => '',
                'category_id' => 6,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Kalijira Chal',
                'slug' => 'kalijira-chal',
                'short_description' => 'Tiny-grained aromatic Kalijira rice.',
                'description' => 'Kalijira Chal is a traditional Bangladeshi aromatic rice with small grains, ideal for fine cooking and traditional meals.',
                'regular_price' => 150.00,
                'sale_price' => 140.00,
                'SKU' => 'SKU-KALIJIRA-CHAL',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/rice/5.jpg',
                'images' => '',
                'category_id' => 6,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ===========================Lentils (Dal-5)==============================
            [
                'name' => 'Masoor Dal',
                'slug' => 'masoor-dal',
                'short_description' => 'Red lentils packed with protein.',
                'description' => 'Masoor Dal is a staple in Bengali households, rich in protein and fiber, perfect for everyday meals.',
                'regular_price' => 90.00,
                'sale_price' => 85.00,
                'SKU' => 'SKU-MASOOR-DAL',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 150,
                'image' => 'products/kacha_bazar/lentils/1.jpg',
                'images' => '',
                'category_id' => 7,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Moong Dal',
                'slug' => 'moong-dal',
                'short_description' => 'Light and nutritious yellow lentils.',
                'description' => 'Moong Dal is easy to digest and ideal for making khichuri, dal fry, and traditional comfort foods.',
                'regular_price' => 100.00,
                'sale_price' => 95.00,
                'SKU' => 'SKU-MOONG-DAL',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 150,
                'image' => 'products/kacha_bazar/lentils/2.jpg',
                'images' => '',
                'category_id' => 7,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Chana Dal',
                'slug' => 'chana-dal',
                'short_description' => 'Split chickpeas full of flavor.',
                'description' => 'Chana Dal is great for curries and savory snacks, offering a rich texture and nutty flavor.',
                'regular_price' => 110.00,
                'sale_price' => 100.00,
                'SKU' => 'SKU-CHANA-DAL',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 150,
                'image' => 'products/kacha_bazar/lentils/3.jpg',
                'images' => '',
                'category_id' => 7,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Arhar Dal',
                'slug' => 'arhar-dal',
                'short_description' => 'Tasty and nutritious pigeon peas.',
                'description' => 'Arhar Dal, also known as Toor Dal, is commonly used in Indian and Bengali cuisine for making thick and hearty dal.',
                'regular_price' => 105.00,
                'sale_price' => 98.00,
                'SKU' => 'SKU-ARHAR-DAL',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 150,
                'image' => 'products/kacha_bazar/lentils/4.jpg',
                'images' => '',
                'category_id' => 7,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Motor Dal',
                'slug' => 'motor-dal',
                'short_description' => 'Traditional Bengali Motor dal.',
                'description' => 'Motor Dal, or split peas, is perfect for fritters and thick curries, giving a classic taste to home-cooked meals.',
                'regular_price' => 95.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-MOTOR-DAL',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 150,
                'image' => 'products/kacha_bazar/lentils/5.jpg',
                'images' => '',
                'category_id' => 7,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // =============================Vegetables (10 items)=====================================
            [
                'name' => 'Potato',
                'slug' => 'potato',
                'short_description' => 'Fresh farm potatoes.',
                'description' => 'Locally sourced fresh potatoes, perfect for daily cooking and a rich source of carbs.',
                'regular_price' => 30.00,
                'sale_price' => 25.00,
                'SKU' => 'SKU-POTATO',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 300,
                'image' => 'products/kacha_bazar/vegetables/1.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Onion',
                'slug' => 'onion',
                'short_description' => 'Fresh red onions.',
                'description' => 'A kitchen essential, these onions add flavor and aroma to any dish.',
                'regular_price' => 40.00,
                'sale_price' => 35.00,
                'SKU' => 'SKU-ONION',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 300,
                'image' => 'products/kacha_bazar/vegetables/2.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Tomato',
                'slug' => 'tomato',
                'short_description' => 'Juicy red tomatoes.',
                'description' => 'Fresh and juicy tomatoes, perfect for salads, cooking, and sauces.',
                'regular_price' => 45.00,
                'sale_price' => 40.00,
                'SKU' => 'SKU-TOMATO',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 300,
                'image' => 'products/kacha_bazar/vegetables/3.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Carrot',
                'slug' => 'carrot',
                'short_description' => 'Crunchy carrots full of nutrition.',
                'description' => 'Bright orange carrots packed with vitamins, perfect for both raw and cooked dishes.',
                'regular_price' => 50.00,
                'sale_price' => 45.00,
                'SKU' => 'SKU-CARROT',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 300,
                'image' => 'products/kacha_bazar/vegetables/4.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cabbage',
                'slug' => 'cabbage',
                'short_description' => 'Fresh green cabbage.',
                'description' => 'Organically grown cabbage, great for curries and salads.',
                'regular_price' => 35.00,
                'sale_price' => 30.00,
                'SKU' => 'SKU-CABBAGE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 300,
                'image' => 'products/kacha_bazar/vegetables/5.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cauliflower',
                'slug' => 'cauliflower',
                'short_description' => 'Fresh white cauliflower.',
                'description' => 'Farm-fresh cauliflower, ideal for curries, fries, or healthy salads.',
                'regular_price' => 45.00,
                'sale_price' => 40.00,
                'SKU' => 'SKU-CAULIFLOWER',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 250,
                'image' => 'products/kacha_bazar/vegetables/6.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Spinach',
                'slug' => 'spinach',
                'short_description' => 'Fresh green spinach leaves.',
                'description' => 'Nutritious and fresh spinach, great for cooking or making healthy smoothies.',
                'regular_price' => 30.00,
                'sale_price' => 25.00,
                'SKU' => 'SKU-SPINACH',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 250,
                'image' => 'products/kacha_bazar/vegetables/7.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ladyfinger',
                'slug' => 'ladyfinger',
                'short_description' => 'Fresh ladyfinger (okra).',
                'description' => 'Tender ladyfingers full of fiber and nutrients, perfect for stir-fries and curries.',
                'regular_price' => 35.00,
                'sale_price' => 30.00,
                'SKU' => 'SKU-LADYFINGER',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 250,
                'image' => 'products/kacha_bazar/vegetables/8.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pumpkin',
                'slug' => 'pumpkin',
                'short_description' => 'Sweet and soft pumpkin.',
                'description' => 'Delicious and soft pumpkin, ideal for curries, soups, or traditional dishes.',
                'regular_price' => 28.00,
                'sale_price' => 25.00,
                'SKU' => 'SKU-PUMPKIN',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 250,
                'image' => 'products/kacha_bazar/vegetables/9.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Bottle Gourd',
                'slug' => 'bottle-gourd',
                'short_description' => 'Fresh bottle gourd (lau).',
                'description' => 'Hydrating and healthy bottle gourd, known for its cooling properties and versatility.',
                'regular_price' => 32.00,
                'sale_price' => 28.00,
                'SKU' => 'SKU-BOTTLE-GOURD',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 250,
                'image' => 'products/kacha_bazar/vegetables/10.jpg',
                'images' => '',
                'category_id' => 8,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // =====================🍍 Fruits (10)===============================
            [
                'name' => 'Banana',
                'slug' => 'banana',
                'short_description' => 'Fresh ripe bananas.',
                'description' => 'Naturally sweet bananas packed with energy and potassium, perfect for snacks and smoothies.',
                'regular_price' => 25.00,
                'sale_price' => 20.00,
                'SKU' => 'SKU-BANANA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 300,
                'image' => 'products/kacha_bazar/fruits/1.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Apple',
                'slug' => 'apple',
                'short_description' => 'Juicy and crunchy apples.',
                'description' => 'Crisp red apples rich in fiber and antioxidants. Great for snacks or desserts.',
                'regular_price' => 120.00,
                'sale_price' => 110.00,
                'SKU' => 'SKU-APPLE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/fruits/2.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mango',
                'slug' => 'mango',
                'short_description' => 'Seasonal sweet mangoes.',
                'description' => 'Luscious mangoes full of flavor. A summertime favorite in every household.',
                'regular_price' => 100.00,
                'sale_price' => 90.00,
                'SKU' => 'SKU-MANGO',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 250,
                'image' => 'products/kacha_bazar/fruits/3.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Guava',
                'slug' => 'guava',
                'short_description' => 'Crunchy green guavas.',
                'description' => 'Fiber-rich and vitamin-packed guavas with a refreshing flavor and aroma.',
                'regular_price' => 45.00,
                'sale_price' => 40.00,
                'SKU' => 'SKU-GUAVA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/fruits/4.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Papaya',
                'slug' => 'papaya',
                'short_description' => 'Freshly cut papaya.',
                'description' => 'Nutritious papaya loaded with digestive enzymes and vitamins. Great for your health.',
                'regular_price' => 30.00,
                'sale_price' => 25.00,
                'SKU' => 'SKU-PAPAYA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 220,
                'image' => 'products/kacha_bazar/fruits/5.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Watermelon',
                'slug' => 'watermelon',
                'short_description' => 'Juicy red watermelon.',
                'description' => 'Cool and hydrating watermelon, perfect for summer refreshment. Full of vitamins A and C.',
                'regular_price' => 80.00,
                'sale_price' => 70.00,
                'SKU' => 'SKU-WATERMELON',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 180,
                'image' => 'products/kacha_bazar/fruits/6.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pineapple',
                'slug' => 'pineapple',
                'short_description' => 'Fresh juicy pineapple.',
                'description' => 'Tropical and tangy pineapple rich in vitamin C. Great for digestion and flavor enhancement.',
                'regular_price' => 60.00,
                'sale_price' => 55.00,
                'SKU' => 'SKU-PINEAPPLE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 160,
                'image' => 'products/kacha_bazar/fruits/7.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Grapes',
                'slug' => 'grapes',
                'short_description' => 'Sweet green grapes.',
                'description' => 'Juicy and antioxidant-rich grapes. Great as snacks or for making juice.',
                'regular_price' => 90.00,
                'sale_price' => 80.00,
                'SKU' => 'SKU-GRAPES',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 140,
                'image' => 'products/kacha_bazar/fruits/8.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pomegranate',
                'slug' => 'pomegranate',
                'short_description' => 'Red pomegranate seeds.',
                'description' => 'Loaded with antioxidants and nutrients, pomegranates boost heart health and immunity.',
                'regular_price' => 110.00,
                'sale_price' => 100.00,
                'SKU' => 'SKU-POMEGRANATE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 130,
                'image' => 'products/kacha_bazar/fruits/9.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dates',
                'slug' => 'dates',
                'short_description' => 'Soft sweet dates.',
                'description' => 'Nutrient-packed dates, naturally sweet and a great energy booster. Ideal for snacking or cooking.',
                'regular_price' => 150.00,
                'sale_price' => 140.00,
                'SKU' => 'SKU-DATES',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 100,
                'image' => 'products/kacha_bazar/fruits/10.jpg',
                'images' => '',
                'category_id' => 9,
                'brand_id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ================================Spices & Masala(10)============================
            [
                'name' => 'Turmeric Powder',
                'slug' => 'turmeric-powder',
                'short_description' => 'Pure turmeric powder.',
                'description' => 'Bright yellow turmeric powder, perfect for adding color and health benefits to your dishes.',
                'regular_price' => 50.00,
                'sale_price' => 45.00,
                'SKU' => 'SKU-TURMERIC',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/spices/1.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Chili Powder',
                'slug' => 'chili-powder',
                'short_description' => 'Spicy chili powder.',
                'description' => 'Hot and spicy red chili powder to add that perfect kick to your recipes.',
                'regular_price' => 60.00,
                'sale_price' => 55.00,
                'SKU' => 'SKU-CHILI',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 180,
                'image' => 'products/kacha_bazar/spices/2.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Coriander Powder',
                'slug' => 'coriander-powder',
                'short_description' => 'Fragrant coriander powder.',
                'description' => 'Ground coriander seeds bringing a mild, citrusy flavor to your everyday cooking.',
                'regular_price' => 55.00,
                'sale_price' => 50.00,
                'SKU' => 'SKU-CORIANDER',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 170,
                'image' => 'products/kacha_bazar/spices/3.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cumin Powder',
                'slug' => 'cumin-powder',
                'short_description' => 'Aromatic cumin powder.',
                'description' => 'Roasted cumin powder with a rich earthy flavor, a must-have in every kitchen.',
                'regular_price' => 65.00,
                'sale_price' => 60.00,
                'SKU' => 'SKU-CUMIN',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 160,
                'image' => 'products/kacha_bazar/spices/4.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mustard Seeds',
                'slug' => 'mustard-seeds',
                'short_description' => 'Whole mustard seeds.',
                'description' => 'Bold and spicy mustard seeds, great for pickles and Bengali dishes.',
                'regular_price' => 45.00,
                'sale_price' => 40.00,
                'SKU' => 'SKU-MUSTARD-SEEDS',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 150,
                'image' => 'products/kacha_bazar/spices/5.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Bay Leaf',
                'slug' => 'bay-leaf',
                'short_description' => 'Aromatic bay leaves.',
                'description' => 'Dried bay leaves with a subtle fragrance, perfect for curries and biryanis.',
                'regular_price' => 30.00,
                'sale_price' => 25.00,
                'SKU' => 'SKU-BAYLEAF',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 140,
                'image' => 'products/kacha_bazar/spices/6.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Garam Masala',
                'slug' => 'garam-masala',
                'short_description' => 'Mixed spice blend.',
                'description' => 'A flavorful mix of spices to bring warmth and depth to your desi dishes.',
                'regular_price' => 80.00,
                'sale_price' => 75.00,
                'SKU' => 'SKU-GARAM',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 130,
                'image' => 'products/kacha_bazar/spices/7.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Black Pepper',
                'slug' => 'black-pepper',
                'short_description' => 'Whole black pepper.',
                'description' => 'Strong and spicy whole black peppercorns for extra heat and flavor.',
                'regular_price' => 90.00,
                'sale_price' => 85.00,
                'SKU' => 'SKU-PEPPER',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 120,
                'image' => 'products/kacha_bazar/spices/8.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cardamom',
                'slug' => 'cardamom',
                'short_description' => 'Premium green cardamom.',
                'description' => 'Strongly aromatic green cardamom pods used in both sweet and savory dishes.',
                'regular_price' => 150.00,
                'sale_price' => 140.00,
                'SKU' => 'SKU-CARDAMOM',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 100,
                'image' => 'products/kacha_bazar/spices/9.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Clove',
                'slug' => 'clove',
                'short_description' => 'Dried cloves.',
                'description' => 'Strong and pungent dried cloves, a classic spice for curries and biryani.',
                'regular_price' => 120.00,
                'sale_price' => 110.00,
                'SKU' => 'SKU-CLOVE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 110,
                'image' => 'products/kacha_bazar/spices/10.jpg',
                'images' => '',
                'category_id' => 10,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // =================Other Essential Items(10) ===========================
            [
                'name' => 'Sugar',
                'slug' => 'sugar',
                'short_description' => 'Fine white sugar.',
                'description' => 'Refined white sugar perfect for daily cooking and desserts.',
                'regular_price' => 60.00,
                'sale_price' => 55.00,
                'SKU' => 'SKU-SUGAR',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/essentials/1.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Salt',
                'slug' => 'salt',
                'short_description' => 'Pure iodized salt.',
                'description' => 'Everyday iodized salt essential for flavor and nutrition.',
                'regular_price' => 25.00,
                'sale_price' => 22.00,
                'SKU' => 'SKU-SALT',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/essentials/2.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Flour (Atta)',
                'slug' => 'flour-atta',
                'short_description' => 'Fresh wheat flour.',
                'description' => 'Premium quality atta for soft and healthy chapatis.',
                'regular_price' => 70.00,
                'sale_price' => 65.00,
                'SKU' => 'SKU-ATTA',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 150,
                'image' => 'products/kacha_bazar/essentials/3.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mustard Oil',
                'slug' => 'mustard-oil',
                'short_description' => 'Pure mustard oil.',
                'description' => 'Strongly aromatic mustard oil for authentic Bengali cooking.',
                'regular_price' => 160.00,
                'sale_price' => 150.00,
                'SKU' => 'SKU-MUSTOIL',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 100,
                'image' => 'products/kacha_bazar/essentials/4.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ghee',
                'slug' => 'ghee',
                'short_description' => 'Pure cow ghee.',
                'description' => 'Rich and aromatic ghee made from pure cow’s milk.',
                'regular_price' => 300.00,
                'sale_price' => 280.00,
                'SKU' => 'SKU-GHEE',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 80,
                'image' => 'products/kacha_bazar/essentials/5.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 21,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Butter',
                'slug' => 'butter',
                'short_description' => 'Creamy butter.',
                'description' => 'Soft and creamy butter ideal for spreading and cooking.',
                'regular_price' => 180.00,
                'sale_price' => 170.00,
                'SKU' => 'SKU-BUTTER',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 90,
                'image' => 'products/kacha_bazar/essentials/6.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Milk',
                'slug' => 'milk',
                'short_description' => 'Fresh dairy milk.',
                'description' => 'Nutrient-rich fresh milk sourced from local farms.',
                'regular_price' => 60.00,
                'sale_price' => 55.00,
                'SKU' => 'SKU-MILK',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 120,
                'image' => 'products/kacha_bazar/essentials/7.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 22,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cheese',
                'slug' => 'cheese',
                'short_description' => 'Soft processed cheese.',
                'description' => 'Mild and creamy processed cheese, ideal for sandwiches and pasta.',
                'regular_price' => 200.00,
                'sale_price' => 190.00,
                'SKU' => 'SKU-CHEESE',
                'stock_status' => 'in_stock',
                'featured' => false,
                'quantity' => 80,
                'image' => 'products/kacha_bazar/essentials/8.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 22,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Eggs',
                'slug' => 'eggs',
                'short_description' => 'Farm fresh eggs.',
                'description' => 'High-quality farm-fresh eggs, a source of protein and essential nutrients.',
                'regular_price' => 100.00,
                'sale_price' => 95.00,
                'SKU' => 'SKU-EGGS',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 200,
                'image' => 'products/kacha_bazar/essentials/9.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 23,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Chicken',
                'slug' => 'chicken',
                'short_description' => 'Fresh whole chicken.',
                'description' => 'Tender, freshly cut chicken—perfect for curries and grills.',
                'regular_price' => 250.00,
                'sale_price' => 240.00,
                'SKU' => 'SKU-CHICKEN',
                'stock_status' => 'in_stock',
                'featured' => true,
                'quantity' => 100,
                'image' => 'products/kacha_bazar/essentials/10.jpg',
                'images' => '',
                'category_id' => 11,
                'brand_id' => 23,
                'created_at' => $now,
                'updated_at' => $now,
            ]
            // ======================================== End ===========================================
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
